### ISSUE TITLE
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.

### ISSUE THREAD

**Issue by aokugel** [rdbreak/rhcsa8env#21]
Entire error output:

```
    repo: Unable to read consumer identity
    repo: This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
    repo: Extra Packages for Enterprise Linux 7 - x86_64  0.0  B/s |   0  B     02:09
    repo: Failed to synchronize cache for repo 'epel', ignoring this repo.
    repo: Last metadata expiration check: 0:04:22 ago on Wed 28 Oct 2020 04:28:36 PM PDT.
    repo: No match for argument: sshpass
    repo: Package httpd-2.4.37-10.module+el8+2764+7127e69e.x86_64 is already installed.
    repo: No match for argument: sshpass
    repo: Error: Unable to find a match
```

**Comment by rdbreak** [comment]
You should use the included repo server to install packages in this environment unless you want to log into your Red Hat account.

**Comment by aokugel** [comment]
Sorry I should have specified.  This is happening when the vagrant job is doing the initial install/setup.  The vagrant job does the server2 setup fine, but when it gets to the configuration of the repo server, it bombs.  It bombs right after the EPEL installation, so I'm assuming it is somehow related to that.

Thanks!

**Comment by ytra** [comment]
I experienced the same. The VM's are running only the provisioning is not finished correctly. For this to work do the following:
After the failing vagrant up server1 (for example).
vagrant ssh server1
sudo bash
subscription-manager register --auto-attach
Username: Your RedHat account username
Password: Your password
Exit twice and vagrant halt server1 && vagrant up server1
The provisioning will work as expected.

**Comment by JankeeMunkey** [comment]
I dont know if this is the behavior everyone experiences, but for me the subscription issue causes me to need to log into `server-1` and `server-2`, obtain redhat subscription access, and the run `vagrant reload` to continue the configuration of these VMs. I did not, however run into this issue on `repo`. 

I ran into an issue where the steps above were the fix. Issue found [here](https://github.com/lavabit/robox/issues/98)

If I understand correctly, the root reason that the VM requires a red hat subscription to continue the boot process is because the system is attempting to install packages that it needs to perform OS configuration.

A proposal to bypass the need for the subscription at `vagrant up` time is to have vagrant spin the repo server up first and present itself as a useable repository, then have `server-1` and `server-2` next in the vagrantfile, and also have these servers connect to this machine as an rpm repository when ansible does its provisioning for the package installations it requires, then clear the repository settings before it is handed off to the user.
